const GlobalTypes = {
  TOGGLE_SIGNIN_DRAWER: "TOGGLE_SIGNIN_DRAWER",
  TOGGLE_WISHLIST_DRAWER: "TOGGLE_WISHLIST_DRAWER",
  TOGGLE_CART_DRAWER: "TOGGLE_CART_DRAWER",
  TOGGLE_NAVIGATION_DRAWER: "TOGGLE_NAVIGATION_DRAWER",
  TOGGLE_CATEGORY_DRAWER: "TOGGLE_CATEGORY_DRAWER",
};

export default GlobalTypes;
